{
 "title": "RPS- Request per Second",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Notas – Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(app_requests_total{endpoint=\"/notas\"}[1m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"notas-entregable4-chart.*\", container!=\"POD\"}) by (pod)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"notas-entregable4-chart.*\", container!=\"POD\"}[1m])) by (pod)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency – Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(app_request_latency_seconds_sum[1m]))\r\n/\r\nsum(rate(app_request_latency_seconds_count[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS – Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(app_requests_total[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}