apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-cpu-mem-limits
spec:
  validationFailureAction: enforce
  rules:
    - name: check-resources
      match:
        resources:
          kinds: ["Pod"]
      validate:
        message: "Todos los contenedores deben definir limits de CPU y memoria."
        pattern:
          spec:
            containers:
              - resources:
                  limits:
                    memory: "?*"
                    cpu: "?*"
