apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "entregable4-chart.fullname" . }}-pvc
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
